### ISSUE TITLE
EngineErrors

### ISSUE THREAD

**Issue by bhaal166** [cjmanca/FFXIVDBM.Plugin#1]
getting this error now when starting a fight start it didnt do that yesterday

(EngineErrors::Void .ctor(System.WeakReference):0:0: No voice installed on the system or none available with the current security setting.): tts

**Comment by cjmanca** [comment]
Hmm, I'm not sure why that would be happening. Did this just start after you updated?

What operating system are you using?

**Comment by bhaal166** [comment]
ya it started after the update 
windows 8.1 64 bit

**Comment by cjmanca** [comment]
I just released a new update. Please try that and see if it helps this issue.

**Comment by bhaal166** [comment]
yep working fine now thx a lot
