### ISSUE TITLE
Play through Teamspeak

### ISSUE THREAD

**Issue by bhaal166** [cjmanca/FFXIVDBM.Plugin#4]
is it possible to make the tts alert play on teamspeak?

**Comment by cjmanca** [comment]
Yes, I play it out through teamspeak for my static group. You can use the same basic way shown here for ACT:
http://www.archaic-society.com/forums/viewtopic.php?t=10069077

Just ignore the ACT specific setup (you don't need the SlimDX stuff), and in FFXIV-APP, in the "Settings" on the left, then "Peformance & Logging" at the top, set the "Default Audio Device" to "CABLE Input (VB-Audio Virtual Cable)". The rest of the teamspeak and loopback driver install from that guide is still needed.

**Comment by bhaal166** [comment]
thx its working :)
