### ISSUE TITLE
T13 Last Phrase wrong call out

### ISSUE THREAD

**Issue by Darkvelvet** [cjmanca/FFXIVDBM.Plugin#7]
Last phrase, all the call out is being call out randomly at the wrong time and not sync.  It still being call and broadcast even when boss doesn't used any of it ability.  Flatten, Megaflare, etc.

**Comment by cjmanca** [comment]
Hmm, did this start immediately after terraflare, or part way through the final phase? Is this happening every time for you?

I haven't yet experienced this in my runs, but admittedly I've only cleared T13 a small handful of times.

**Comment by Darkvelvet** [comment]
Sometime after Teraflare.  But I know it happens frequently after you died and then res back up again.

**Comment by cjmanca** [comment]
I just farmed T13 for about 20 or so clears, and couldn't replicate this issue. Final phase was called out fine each time for me.

Please make sure you have a chat tab with all filters enabled, to make sure it's not missing a message it's looking for.

**Comment by cjmanca** [comment]
Several months with no reply. Closing issue.
